### ISSUE TITLE
6.0.0 is impossible to install through pip and pypi

### ISSUE THREAD

**Issue by Tcenova** [hdl-registers/hdl-registers#132]
**Description**
6.0.0 release is impossible to install due to conflict of versions between hdl-registers (requires tsfpga >= 12.3.2) and the latest tsfpga (requires <6.0.0 of hdl-registers)

**Expected behavior**
hdl-registers is able to be installed via pip

**How to reproduce?**
pip install hfl-registers==6.0.0

Error should be similar to:

```
ERROR: Cannot install hdl-registers and hdl-registers==6.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested hdl-registers==6.0.0
    tsfpga 12.3.5 depends on hdl-registers<6.0.0 and >=5.1.0
    The user requested hdl-registers==6.0.0
    tsfpga 12.3.4 depends on hdl-registers<6.0.0 and >=5.1.0
    The user requested hdl-registers==6.0.0
    tsfpga 12.3.3 depends on hdl-registers<6.0.0 and >=5.1.0
    The user requested hdl-registers==6.0.0
    tsfpga 12.3.2 depends on hdl-registers<6.0.0 and >=5.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Context**
Please provide the following information:

- Operating system: [Ubuntu 22.04]
- Python version: [3.11.7]
- hdl-registers origin:
  - [x] Released package.
  - [ ] Git repository.
- hdl-registers version: [6.0.0]

**Comment by LukasVik** [comment]
Shit. Yeah that's my mistake. Should be fixed in 6.0.1 which is released now. I will add something in CI so that we can detect problems like this more early in the future.

Thanks for reporting!
